version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper@sha256:2a045b8dc17d407fe7b4e031707f71828a47c4875646381f76825020a610886a'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka@sha256:3422ec506513862893a51e41731c5947c0214d515387f61194768e4f5a971062'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper