MSG_USERID_KEY = "userId"
MSG_CHATID_KEY = "chatId"
MSG_MESSAGEID_KEY = "messageId"
MSG_USERCHANNEL_KEY = "userChannel"

MESSAGE_NAME = "messageName"
MESSAGE_ID = "messageId"
UUID = "uuid"
PAYLOAD = "payload"
SESSION_ID = "sessionId"
