"""
# Описание моделей зарпосов.
"""

from .integration_message import IntegrationMessage, IntegrationPayload, LocalTimeout
from .message import CloseApp, MessageToSkill, RunApp, ServerActionMessage
from .protocol import (
    Annotations,
    AnnotationsDetails,
    AppInfo,
    AssistantMessage,
    AssistantMeta,
    AssistantPayload,
    AssistantState,
    AssistantViewAction,
    AssistantVoiceAction,
    BaseMessage,
    Character,
    CurrentApp,
    Device,
    DeviceCapabilities,
    DeviceCapability,
    DeviceFeatures,
    FeatureLauncher,
    ItemSelector,
    Message,
    MessageToSkillPayload,
    MetaFeature,
    MetaFeatures,
    MetaTime,
    PublicFL,
    RequestData,
    SelectedItem,
    ServerAction,
    ServerActionPayload,
    Strategies,
    UUID,
)

__all__ = [
    Annotations,
    AnnotationsDetails,
    AppInfo,
    AssistantMessage,
    AssistantMeta,
    AssistantPayload,
    AssistantState,
    AssistantViewAction,
    AssistantVoiceAction,
    BaseMessage,
    Character,
    CloseApp,
    CurrentApp,
    Device,
    DeviceCapabilities,
    DeviceCapability,
    DeviceFeatures,
    FeatureLauncher,
    IntegrationMessage,
    IntegrationPayload,
    ItemSelector,
    LocalTimeout,
    Message,
    MessageToSkill,
    MessageToSkillPayload,
    MetaFeature,
    MetaFeatures,
    MetaTime,
    PublicFL,
    RequestData,
    RunApp,
    SelectedItem,
    ServerAction,
    ServerActionMessage,
    ServerActionPayload,
    Strategies,
    UUID,
]
